services:
  - type: web
    name: baconbot
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
